### ISSUE TITLE
When I 澳门

### ISSUE THREAD

**Issue by lihanseu3** [dawenl/expo-mf#6]
File "C:\expo-mf-master\src\expomf_cov.py", line 358, in _solve_batch
    A_batch = a_row_batch(Y[lo:hi], X_old_batch, X, T_batch, S,
  File "C:\expo-mf-master\src\expomf_cov.py", line 333, in a_row_batch
    A = (pEX + EPS) / (pEX + EPS + (1 - mu) / mu)
ValueError: operands could not be broadcast together with shapes (100,33242) (100,45732) 
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 coder.fit(train_data, pi, vad_data=vad_data, batch_users=5000, k=100)

**Comment by lihanseu3** [comment]
What with that I am runing the coder.fit of the expo_cov,But it turns out this.Is there any wrong in the expo_cov
